### ISSUE TITLE
Are we approaching dependency hell?

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-metapkg#7]
While doing aiidalab maintenance I discovered a very frustrating thing that potentially can lead to a considerable amount of problems in the future.

In our dependency stack we have aiida-vasp plugin. Aiida-vasp, in turn, depends on pymatgen that failed to build.

The frustrating thing is: I am not developer/maintainer of any of those packages, but I have to ["manually" fix](https://github.com/aiidalab/aiidalab-metapkg/blob/bcc1f05d4bb8ad891a17b1a1472b0fc3015e7544/requirements.txt#L46) the dependency.

As the number of plugins will grow, the problem will get more and more pronounced.

Another frustrating thing is that aiidalab-metapkg tests could not catch the problem. The problem appeared during the build of aiidalab Docker file. I assume that pip does not have a fixed order of how to install dependencies of dependencies:
* In the first case the aiidalab-metapkg test could pass because another package depends on a **specific version of pymatgen** that was built before aiida-vasp dependencies. 
* In the second case aiida-vasp dependencies were built earlier. Aiida-vasp plugin **does not specify the exact version** of pymatgen, so the latest was taken and this caused the build to fail.

For the moment I can't propose any solution, I should think a bit more on how to approach that.

@giovannipizzi, @ltalirz, @CasperWA any ideas/thoughts? Maybe it was already solved somewhere else? :)

**Comment by ltalirz** [comment]
@yakutovicha Part of the problem, namely the one of creating reproducible builds, is solved by a tool called [pipenv](https://github.com/pypa/pipenv).
 
The basic idea is: instead of a requirements.txt file with fixed dependencies (which, in the end are still not perfectly fixed because of dependencies of dependencies), you create a `Pipenv` file, where you specify the dependency ranges you are interested in (typically you fix MAJOR.MINOR and allow changes in PATH versions).
Then, before you make a release, you let pipenv "concretize" the dependencies down to the very last package that is installed (and you commit `Pipfile.lock` to the repo).

It's used by invenio and I started looking into this for aiidalab a few weeks ago but stopped exactly because of the dependency conflicts that exist.

Of course, pipenv can *not* resolve explicit dependency conflicts that exist between aiida plugins.
I propose our policy should be: if an aiida plugin wants to be present on the AiiDA lab, it must not present any version conflicts with the existing software stack.

I will create a branch with a basic Pipfile and, for the moment, exclude any plugins that present dependency conflicts.

**Comment by ltalirz** [comment]
I started working on this in the [pipenv branch](https://github.com/aiidalab/aiidalab-metapkg/tree/pipenv). Here I'm using pipenv simply to generate a complete `requirements.txt` from the `Pipfile` (instructions added to `README`).

It turns out that, miraculously, all dependency conflicts can be resolved (e.g. `pymatgen` automatically gets resolved to 2018.12.12).

There is [one issue with aiida-fleur](https://github.com/JuDFTteam/aiida-fleur/issues/52) that I opened already more than a month ago and that prevents aiida-fleur from being added.
Once this is fixed, aiida-fleur can be added back to the mix as well.

**Comment by yakutovicha** [comment]
I think pipenv is a great tool. Thanks for looking into that.

Also, I think we should use it while testing aiida plugins. For example it would be nice to create an automated script that installs aiida with all the latest versions of plugins to check incompatibility.

Of course for the moment it is just a wish, nothing concrete. But I think the issue should be solved ASAP, otherwise some users simply won't be able to use aiida because of similar problems.

**Comment by ltalirz** [comment]
Jens just updated aiida-fleur - all packages are now available again (PR #8 updated & ready for review)

**Comment by ltalirz** [comment]
> it would be nice to create an automated script that installs aiida with all the latest versions of plugins to check incompatibilities.

We should define what exactly we want to test here.
As you mention, with `pip` the result might depend on the order of installation.

We could start with a more basic check using pipenv and integrate it into the CI of the aiida plugin registry. I.e. for every new pull request. pipenv would try to concretize the dependencies for installing all plugins together (all that provide a `pip` package name).

**Comment by ltalirz** [comment]
the original issue seems resolved.
discussion about testing continues in https://github.com/aiidateam/aiida-registry/issues/67
